spring:
  datasource:
    url: jdbc:mysql://database-1.czssw6gg4jow.ap-northeast-2.rds.amazonaws.com/security?serverTimezone=Asia/Seoul
    username: simun
    password: woals2133
    driver-class-name: com.mysql.cj.jdbc.Driver

naver:
  client:
    id: TatVie0syM6sUlcRyr1B
    secret: eUggUnq7js
  url:
    search:
      local: https://openapi.naver.com/v1/search/local.json
      image: https://openapi.naver.com/v1/search/image
  maps:
    client:
      id: z9fdx1to2u

mail:
  host: smtp.gmail.com
  port: 587
  username: email-smtp
  password: pvgn mfiv avhz fizm
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true
        connectiontimeout: 5000
        timeout: 5000
        writetimeout: 5000
  auth-code-expiration-millis: 1800000
