spring:
  datasource:
    url: jdbc:mysql://database-1.czssw6gg4jow.ap-northeast-2.rds.amazonaws.com/security?serverTimezone=Asia/Seoul
    username: simun
    password: woals2133
    driver-class-name: com.mysql.cj.jdbc.Driver