server:
  port: ${server.port:8080}  # ??? 8080
  config:
    activate:
      on-profile: ${server.config.activate.on-profile:local}
  serverAddress: ${server.serverAddress:localhost}
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  error:
    whitelabel:
      enabled: false
    path: /error
  env: blue
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  profiles:
    active: local
    group:
      local: local, common, secret
      blue: blue, common, secret
      green: green, common, secret

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    config:
      activate:
        on-profile: common
    oauth2:
      client:
        registration:
          google:
            client-id: 548751246735-i3st71h8r22uvr8jhl7d44d01pt7g8dm.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
          naver:
            client-id: eIvKv0fVk3F91SiQY8FW
            client-secret: p1s0EWxv_H
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  thymeleaf:
    prefix: classpath:/templates/
    cache: false

  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USERNAME:email-smtp}
    password: ${SMTP_PASSWORD:pvgn mfiv avhz fizm}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: HomePage.domain.model.entity
  configuration:
    map-underscore-to-camel-case: true

communityBoard:
  page-size: 10

reviewBoard:
  page-size: 20

jwt:
  secret: "COS"
  expiration: 600000

mail:
  host: smtp.gmail.com
  port: 587
  username: email-smtp
  password: pvgn mfiv avhz fizm
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true
        connectiontimeout: 5000
        timeout: 5000
        writetimeout: 5000
  auth-code-expiration-millis: 1800000

naver:
  client:
    id: TatVie0syM6sUlcRyr1B
    secret: eUggUnq7js
  url:
    search:
      local: https://openapi.naver.com/v1/search/local.json
      image: https://openapi.naver.com/v1/search/image


# Redis ?? (?? ?????)
#spring:
#  redis:
#    host: localhost
#    port: 6379

---
spring:
  config:
    activate:
      on-profile: blue
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://13.124.17.205/login/oauth2/code/google
          naver:
            redirect-uri: http://13.124.17.205/login/oauth2/code/naver


server:
  port: 8080
  serverAddress: 13.124.17.205
serverName: blue_server

---
spring:
  config:
    activate:
      on-profile: green
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://13.124.17.205/login/oauth2/code/google
          naver:
            redirect-uri: http://13.124.17.205/login/oauth2/code/naver


server:
  port: 8081
  serverAddress: 13.124.17.205
serverName: green_server

---
spring:
  config:
    activate:
      on-profile: local
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:8080/login/oauth2/code/google
          naver:
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

server:
  port: 8080
  serverAddress: localhost
serverName: local_server